name: Build and publish jar packages
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
        - Major
        - Minor
        - Patch
        - Snapshot
      publish_to_maven:
        description: 'True to publish the artifacts to maven repository, false to skip the step'
        default: false
        required: false
        type: boolean
      java_version:
        type: string
        default: '11'
      publish_vulnerabilities:
        type: string
        default: 'true'
  pull_request:

jobs:
  build-and-pubish:
    name: Build and publish JAR Packages to Maven Repos
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-java-publish-versioned-package.yaml@main
    with:
      release_type: ${{ inputs.release_type }}
      publish_to_maven: ${{ inputs.publish_to_maven }}
      java_version: ${{ inputs.java_version }}
      publish_vulnerabilities: ${{ inputs.publish_vulnerabilities }}
    secrets: inherit