name: Build and Publish JAR Packages
run-name: ${{ inputs.release_type == 'Snapshot' && 'Publish pre-release' || format('Release {0}', inputs.release_type)}} Package by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
        - Snapshot
        - Patch
        - Minor
        - Major
      vulnerability_failure_severity:
        description: The severity to fail the workflow if such vulnerability is detected. DO NOT override it unless a Jira ticket is raised.
        type: choice
        options:
        - CRITICAL,HIGH
        - CRITICAL,HIGH,MEDIUM
        - CRITICAL (DO NOT use if JIRA ticket not raised)
      publish_to_maven:
        description: 'True to publish the artifacts to Maven repository, false to skip the step'
        default: true
        required: false
        type: boolean
      java_version:
        type: string
        default: '21'
      publish_vulnerabilities:
        type: string
        default: 'true'

jobs:
  build-and-pubish:
    name: Build and publish JAR packages to Maven repository
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-to-maven-versioned.yaml@v2
    with:
      release_type: ${{ inputs.release_type }}
      publish_to_maven: ${{ inputs.publish_to_maven }}
      java_version: ${{ inputs.java_version }}
      publish_vulnerabilities: ${{ inputs.publish_vulnerabilities }}
      vulnerability_failure_severity: ${{ inputs.vulnerability_failure_severity }}
    secrets: inherit
