name: Publish Major Package
on:
  workflow_dispatch:

jobs:
  build-publish-package:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-java-publish-versioned-package.yaml@main
    with: 
      release_type: 'Major'
    secrets: inherit
